// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function CancelWebLogin() {
  return window['go']['main']['App']['CancelWebLogin']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CopyNodeShareLink(arg1) {
  return window['go']['main']['App']['CopyNodeShareLink'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteNodes(arg1) {
  return window['go']['main']['App']['DeleteNodes'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStartError() {
  return window['go']['main']['App']['GetAutoStartError']();
}

export function GetCoreStatus() {
  return window['go']['main']['App']['GetCoreStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetUpdateProgress() {
  return window['go']['main']['App']['GetUpdateProgress']();
}

export function ImportNodesFromClipboard() {
  return window['go']['main']['App']['ImportNodesFromClipboard']();
}

export function ImportNodesFromLinks(arg1) {
  return window['go']['main']['App']['ImportNodesFromLinks'](arg1);
}

export function IsAutoPinging() {
  return window['go']['main']['App']['IsAutoPinging']();
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PingAllNodes() {
  return window['go']['main']['App']['PingAllNodes']();
}

export function PingNode(arg1) {
  return window['go']['main']['App']['PingNode'](arg1);
}

export function PingNodes(arg1) {
  return window['go']['main']['App']['PingNodes'](arg1);
}

export function RefreshAccount() {
  return window['go']['main']['App']['RefreshAccount']();
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectNode(arg1) {
  return window['go']['main']['App']['SelectNode'](arg1);
}

export function SetRoutingMode(arg1) {
  return window['go']['main']['App']['SetRoutingMode'](arg1);
}

export function SimpleConnect(arg1) {
  return window['go']['main']['App']['SimpleConnect'](arg1);
}

export function SkipLogin() {
  return window['go']['main']['App']['SkipLogin']();
}

export function StartAutoPing() {
  return window['go']['main']['App']['StartAutoPing']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function StartWebLogin() {
  return window['go']['main']['App']['StartWebLogin']();
}

export function SyncNodes() {
  return window['go']['main']['App']['SyncNodes']();
}

export function ToggleCore(arg1) {
  return window['go']['main']['App']['ToggleCore'](arg1);
}

export function ToggleSystemProxy(arg1) {
  return window['go']['main']['App']['ToggleSystemProxy'](arg1);
}

export function UpdateNode(arg1) {
  return window['go']['main']['App']['UpdateNode'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMax() {
  return window['go']['main']['App']['WindowMax']();
}

export function WindowMin() {
  return window['go']['main']['App']['WindowMin']();
}
