// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddNode(arg1:main.NodeItem):Promise<void>;

export function CancelWebLogin():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearLogs():Promise<void>;

export function CopyNodeShareLink(arg1:string):Promise<boolean>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeleteNodes(arg1:Array<string>):Promise<void>;

export function GetAccount():Promise<main.AccountInfo>;

export function GetAppVersion():Promise<string>;

export function GetAutoStartError():Promise<string>;

export function GetCoreStatus():Promise<main.CoreStatus>;

export function GetLogs():Promise<Array<main.LogItem>>;

export function GetNodes():Promise<Array<main.NodeItem>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSubscriptions():Promise<Array<main.SubscriptionItem>>;

export function GetUpdateProgress():Promise<main.UpdateProgress>;

export function ImportNodesFromClipboard():Promise<number>;

export function ImportNodesFromLinks(arg1:string):Promise<number>;

export function IsAutoPinging():Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.AccountInfo>;

export function Logout():Promise<main.AccountInfo>;

export function PingAllNodes():Promise<Array<main.NodeItem>>;

export function PingNode(arg1:string):Promise<number>;

export function PingNodes(arg1:Array<string>):Promise<Array<main.NodeItem>>;

export function RefreshAccount():Promise<main.AccountInfo>;

export function RestartCore():Promise<main.CoreStatus>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectNode(arg1:string):Promise<main.NodeItem>;

export function SetRoutingMode(arg1:string):Promise<boolean>;

export function SimpleConnect(arg1:boolean):Promise<boolean>;

export function SkipLogin():Promise<main.AccountInfo>;

export function StartAutoPing():Promise<void>;

export function StartUpdate():Promise<void>;

export function StartWebLogin():Promise<string>;

export function SyncNodes():Promise<void>;

export function ToggleCore(arg1:boolean):Promise<boolean>;

export function ToggleSystemProxy(arg1:boolean):Promise<boolean>;

export function UpdateNode(arg1:main.NodeItem):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMax():Promise<void>;

export function WindowMin():Promise<void>;
